name: Publish test Docker Image II
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./lesson-4-automating-development/exercises/travis_ci
          file: ./lesson-4-automating-development/exercises/travis_ci/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simple-node